name: Python application

on:
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1

    - name: Set up Python 3.7
      uses: actions/setup-python@v1
      with:
        python-version: 3.7

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Lint with black
      run: black .

    - name: Test with pytest
      run: pytest

    - name: Run deployment script
      run: |
        python create_deployment.py auth3 estensen/auth-v2 "auth"
        python deploy.py

    - name: Add changes
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git commit -m "Add pipeline" -a

    - name: Commit
      uses: ad-m/github-push-action@master
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}

    - name: Merge and delete branch
      uses: estensen/auto_merge_my_pull_requests@master
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
